version: "3.8"

services:
  gifts_sniper:
    build: .
    container_name: sniper_bot
    restart: always
    volumes:
      - ./data:/usr/src/app/data # монтируем data внутрь контейнера
    environment:
      - PYTHONUNBUFFERED=1 # чтобы логи сразу шли в stdout
